{% set name = "mamba" %}
{% set version = "0.7.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/mamba/archive/{{ version }}.tar.gz
  sha256: ef4d0fb2c69d96dfa27071bfbb2f562bdf358875ef400d52e9be3e60be1ce89a

build:
  number: 0
  entry_points:
    - mamba = mamba.mamba:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - python
    - pip
    - pybind11
    - conda >=4.8
    - libsolv >=0.7.16
    - libcurl
    - openssl
    - libarchive
    - nlohmann_json
    - cpp-filesystem
    - reproc-cpp >=14.2.1
    - libiconv                                # [unix]
  run:
    - python
    - conda >=4.8

test:
  imports:
    - mamba
    - mamba.mamba_api
  commands:
    - mamba --help
    # these tests work when run on win, but for some reason not during conda build
    - mamba create -n test_py2 python=2.7 --dry-run  # [linux]
    - mamba install xtensor xsimd -c conda-forge --dry-run  # [linux and x86_64]

about:
  home: https://github.com/mamba-org/mamba
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - CPP_FILESYSTEM_LICENSE.txt
  license_family: BSD
  summary: A fast drop-in alternative to conda, using libsolv for dependency resolution
  description: A fast drop-in alternative to conda, using libsolv for dependency resolution
  dev_url: https://github.com/mamba-org/mamba

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - ericmjl
