{% set name = "mamba" %}
{% set version = "0.5.1" %}
{% set sha256 = "2c719d2fa623205672652cc21af15b052434ce5330fcbed01b4b921f22ba9e62" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TheSnakePit/mamba/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]
  entry_points:
    - mamba = mamba.mamba:main

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - python
    - pip
    - pybind11
    - conda >=4.8
    - libsolv >=0.7.14
    - libcurl
    - openssl
    - libarchive
    - nlohmann_json
    - cpp-filesystem
  run:
    - python
    - conda >=4.8

outputs:
  - name: mamba
    script: build.sh  # [unix]
    script: build.bat  # [win]
    test:
      imports:
        - mamba
        - mamba.mamba_api
      commands:
        - mamba --help
        # these tests work when run on win, but for some reason not during conda build
        - mamba create -n test_py2 python=2.7 --dry-run  # [linux]
        - mamba install xtensor xsimd -c conda-forge --dry-run  # [linux and x86_64]

  - name: libmamba
    script: build_lib.sh  # [unix]
    requirements:
      build:
        - cmake
        - ninja
        - {{ compiler('cxx') }}
      host:
        - libsolv >=0.7.14
        - libcurl
        - openssl
        - libarchive
        - nlohmann_json
        - cpp-filesystem
    test:
      commands:
        - test -f $PREFIX/lib/libmamba.so
        - test -f $PREFIX/include/mamba/context.hpp
        - test -f $PREFIX/include/mamba/channel.hpp

about:
  home: https://github.com/TheSnakePit/mamba
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A fast drop-in alternative to conda, using libsolv for dependency resolution
  description: A fast drop-in alternative to conda, using libsolv for dependency resolution
  dev_url: https://github.com/TheSnakePit/mamba

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - ericmjl
