{% set name = "mamba" %}
{% set version = "0.0.9" %}
{% set sha256 = "99610fcae871c44465ae5daa629f048fbc66130937726abbba8c4ce65a729eef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/QuantStack/mamba/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  # script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - mamba = mamba.mamba:main

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - python
    - pip
    - pybind11 2.2.*
    - conda 4.6.*|4.7.*
    - libsolv 0.7.5
  run:
    - python
    - conda 4.6.*|4.7.*

test:
  imports:
    - mamba
    - mamba.mamba_api
  commands:
    - mamba --help
    - mamba install python=2.7 --dry-run

about:
  home: https://github.com/QuantStack/mamba
  license: BSD 3-Clause
  license_family: BSD
  summary: 'A faster conda?!'
  description: 'mamba, a (hopefully faster) reimplementation of parts of conda.'
  dev_url: https://github.com/QuantStack/mamba

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
