{% set name = "mamba" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/mamba/archive/{{ version }}.tar.gz
  sha256: 70194c6a0e3905b1426004df3f889ae6768559f24037631c644dc9208a072611

build:
  number: 0
  skip: true  # [win and vc<14]
  entry_points:
    - mamba = mamba.mamba:main

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - python
    - pip
    - pybind11
    - conda >=4.8
    - libsolv >=0.7.14
    - libcurl
    - openssl
    - libarchive
    - libiconv
    - nlohmann_json
    - cpp-filesystem
  run:
    - python
    - conda >=4.8

test:
  imports:
    - mamba
    - mamba.mamba_api
  commands:
    - mamba --help
    # these tests work when run on win, but for some reason not during conda build
    - mamba create -n test_py2 python=2.7 --dry-run  # [linux]
    - mamba install xtensor xsimd -c conda-forge --dry-run  # [linux and x86_64]

about:
  home: https://github.com/mamba-org/mamba
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - CPP_FILESYSTEM_LICENSE.txt
  license_family: BSD
  summary: A fast drop-in alternative to conda, using libsolv for dependency resolution
  description: A fast drop-in alternative to conda, using libsolv for dependency resolution
  dev_url: https://github.com/mamba-org/mamba

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - ericmjl
