{% set name = "mamba" %}
{% set version = "0.0.6" %}
{% set sha256 = "ebc7afb7b62b85059b1c23e7aaa9acfa2630e0fa9ed147d824e81005949b0d8d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/QuantStack/mamba/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - mamba = mamba.mamba:main

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - python
    - pip
    - pybind11 2.2.*
    - conda 4.6.*
    - libsolv 0.7.4 conda_experimental3
  run:
    - python
    - conda 4.6.*

test:
  imports:
    - mamba
    - mamba.mamba_api
  commands:
    - mamba --help  # [not win]

about:
  home: https://github.com/QuantStack/mamba
  license: BSD 3-Clause
  license_family: BSD
  summary: 'A faster conda?!'
  description: 'mamba, a (hopefully faster) reimplementation of parts of conda.'
  dev_url: https://github.com/QuantStack/mamba

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
