{% set name = "mamba" %}
{% set version = "0.2.5" %}
{% set sha256 = "8f7b9d0e72551bf6722d6112d0078584f834b3bd6389a6b497f790596a0adddb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/QuantStack/mamba/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and vc<14]
  entry_points:
    - mamba = mamba.mamba:main

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - python
    - pip
    - pybind11
    - conda >=4.8
    - libsolv >=0.7.12
    - libcurl
    - openssl
    - libarchive
    - nlohmann_json
  run:
    - python
    - conda >=4.8

test:
  imports:
    - mamba
    - mamba.mamba_api
  commands:
    - mamba --help
    # these tests work when run on win, but for some reason not during conda build
    - mamba create -n test_py2 python=2.7 --dry-run  # [linux]
    - mamba install xtensor xsimd -c conda-forge --dry-run  # [linux]

about:
  home: https://github.com/QuantStack/mamba
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A fast drop-in alternative to conda, using libsolv for dependency resolution
  description: A fast drop-in alternative to conda, using libsolv for dependency resolution
  dev_url: https://github.com/QuantStack/mamba

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
