{% set name = "mamba" %}
{% set version = "0.1.0" %}
{% set sha256 = "5150081d5b43bd2e34226172590dbea5b61a1ae9621e049a809e49c1047debfb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/QuantStack/mamba/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - mamba_osx.patch  # [osx]

build:
  number: 3
  skip: true  # [win and vc<14]
  entry_points:
    - mamba = mamba.mamba:main

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - python
    - pip
    - pybind11 2.3.*
    - conda >=4.7.12
    - libsolv >=0.7.9
  run:
    - python
    - conda >=4.7.12

test:
  imports:
    - mamba
    - mamba.mamba_api
  commands:
    - mamba --help
    # these tests work when run on win, but for some reason not during conda build
    - mamba create -n test_py2 python=2.7 --dry-run  # [not win]
    - mamba install xtensor xsimd -c conda-forge --dry-run  # [not win]

about:
  home: https://github.com/QuantStack/mamba
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'A faster conda?!'
  description: 'mamba, a (hopefully faster) reimplementation of parts of conda.'
  dev_url: https://github.com/QuantStack/mamba

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
