{% set name = "mamba" %}
{% set libmamba_version = "0.27.0" %}
{% set libmambapy_version = "0.27.0" %}
{% set mamba_version = "0.27.0" %}
{% set release = "2022.10.04" %}

package:
  name: mamba-split

source:
  url: https://github.com/mamba-org/mamba/archive/refs/tags/{{ release }}.tar.gz
  sha256: d4d4fbcfdb05794bb80ec87d9e61eb493b1827a78227b137684add2b9792f01e

build:
  number: 1

outputs:
  - name: libmamba
    version: {{ libmamba_version }}
    script: build_mamba.sh                       # [unix]
    script: build_mamba.bat                      # [win]
    build:
      run_exports:
        - {{ pin_subpackage('libmamba', max_pin='x.x') }}
      ignore_run_exports:
        - spdlog
        - python  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - python  # [win]
      host:
        - libsolv >=0.7.19
        - libcurl
        - openssl
        - libarchive
        - nlohmann_json
        - cpp-expected
        - reproc-cpp >=14.2.1
        - spdlog
        - yaml-cpp
        - termcolor-cpp
        - cli11
        - libiconv                               # [unix]
        - winreg                                 # [win]
    test:
      commands:
        - test -d ${PREFIX}/include/mamba  # [unix]
        - test -f ${PREFIX}/include/mamba/version.hpp  # [unix]
        - test -f ${PREFIX}/lib/cmake/libmamba/libmambaConfig.cmake  # [unix]
        - test -f ${PREFIX}/lib/cmake/libmamba/libmambaConfigVersion.cmake  # [unix]
        - test -e ${PREFIX}/lib/libmamba${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_PREFIX%\include\mamba\version.hpp (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\libmamba\libmambaConfig.cmake (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\libmamba\libmambaConfigVersion.cmake (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\bin\libmamba.dll (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\libmamba.lib (exit 1)  # [win]
        {% set libmamba_version_split = libmamba_version.split('.') %}
        - cat $PREFIX/include/mamba/version.hpp | grep "LIBMAMBA_VERSION_MAJOR {{ libmamba_version_split[0] }}"  # [unix]
        - cat $PREFIX/include/mamba/version.hpp | grep "LIBMAMBA_VERSION_MINOR {{ libmamba_version_split[1] }}"  # [unix]
        - cat $PREFIX/include/mamba/version.hpp | grep "LIBMAMBA_VERSION_PATCH {{ libmamba_version_split[2] }}"  # [unix]

  - name: libmambapy
    version: {{ libmambapy_version }}
    script: build_mamba.sh                       # [unix]
    script: build_mamba.bat                      # [win]
    build:
      string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      run_exports:
        - {{ pin_subpackage('libmambapy', max_pin='x.x') }}
      ignore_run_exports:
        - spdlog
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        - pybind11-abi                           # [build_platform != target_platform]
      host:
        - python
        - pip
        - pybind11
        - pybind11-abi
        - openssl
        - yaml-cpp
        - cpp-expected
        - spdlog
        - termcolor-cpp
        - nlohmann_json
        - {{ pin_subpackage('libmamba', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('libmamba', exact=True) }}

    test:
      imports:
        - libmambapy
        - libmambapy.bindings
      commands:
        - python -c "import libmambapy._version; assert libmambapy._version.__version__ == '{{ libmambapy_version }}'"

  - name: mamba
    version: {{ mamba_version }}
    script: build_mamba.sh                       # [unix]
    script: build_mamba.bat                      # [win]
    build:
      string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      entry_points:
        - mamba = mamba.mamba:main
    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
      host:
        - python
        - pip
        - openssl
        - {{ pin_subpackage('libmambapy', exact=True) }}
      run:
        - python
        - conda >=4.8,<23.4
        - {{ pin_subpackage('libmambapy', exact=True) }}

    test:
      imports:
        - mamba
      requires:
        - pip
      commands:
        - mamba --help
        - if exist %PREFIX%\condabin\mamba.bat (exit 0) else (exit 1)  # [win]
        - test -f ${PREFIX}/etc/profile.d/mamba.sh  # [linux]
        # these tests work when run on win, but for some reason not during conda build
        - mamba create -n test_py2 python=2.7 --dry-run  # [linux]
        - mamba install xtensor xsimd -c conda-forge --dry-run  # [linux and x86_64]
        # for some reason tqdm doesn't have a proper colorama dependency so pip check fails
        # but that's completely unrelated to mamba
        - python -c "import mamba._version; assert mamba._version.__version__ == '{{ mamba_version }}'"
        - test -f ${PREFIX}/condabin/mamba  # [unix]

about:
  home: https://github.com/mamba-org/mamba
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A fast drop-in alternative to conda, using libsolv for dependency resolution
  description: A fast drop-in alternative to conda, using libsolv for dependency resolution
  dev_url: https://github.com/mamba-org/mamba

extra:
  recipe-maintainers:
    - adriendelsalle
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - ericmjl
