bot:
  abi_migration_branches:
  - 1.x
  - prerelease
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_build_tool: rattler-build
conda_install_tool: pixi
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
  win_64: azure
test: native_and_emulated
